# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  carvedrockapi:
    build:
      context: .
      dockerfile: CarvedRock.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "8080:5202"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SimpleProperty=hello-from-compose
      - SeqUrl=http://seq_in_dc:5341
      - RabbitMqHost=rabbit_in_dc
    depends_on:
      - seq_in_dc
      - rabbit_in_dc
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  carvedrockapp:
    build:
      context: .
      dockerfile: CarvedRock.App/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "8081:5298"
    environment:
      - SeqUrl=http://seq_in_dc:5341
      - CarvedRockApiUrl=http://carvedrockapi:5202
    depends_on:
      - seq_in_dc
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  carvedrockorederprocessor:
    build:
      context: .
      dockerfile: CarvedRock.OrderProcessor/Dockerfile
      args:
        - configuration=Debug
    environment:
      - SeqUrl=http://seq_in_dc:5341
      - RabbitMqHost=rabbit_in_dc
    depends_on:
      - seq_in_dc
      - rabbit_in_dc
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      
  seq_in_dc:
    image: datalust/seq
    ports:
      - "8005:80"
    environment:
      - ACCEPT_EULA=Y

  rabbit_in_dc:
    image: rabbitmq:3-management
    ports:
      - 8088:15672
