<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>1af3224b-b5a9-483a-b2cb-157a5772522e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\eShop.ApiService\eShop.ApiService.csproj" />
    <ProjectReference Include="..\eShop.Web\eShop.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.2.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="8.0.0" />
  </ItemGroup>

</Project>
